---
- name: "Check if cargo is installed"
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: "Install and configure rustup"
  when: cargo_exists is failed
  block:
    - name: "Download rustup"
      ansible.builtin.get_url:
        url: "{{ rust_rustup_url }}"
        dest: /tmp/sh.rustup.rs
        mode: "0755"
        force: true
    - name: "Install rust"
      ansible.builtin.shell:
        cmd: /tmp/sh.rustup.rs -y
