---
- name: "Set user home directory fact"
  hosts: local
  connection: local
  gather_facts: false
  roles:
    - user_home

- name: "Configure Ubuntu 22.04"
  hosts: local
  connection: local
  roles:
    - role: authorized_keys
      become: true
    - aws_cliv2
    - dotfiles
    - umask
