---
- name: "Set user home directory fact"
  hosts: local
  connection: local
  gather_facts: false
  roles:
    - user_home

- name: "Configure Ubuntu 22.04"
  hosts: local
  connection: local
  roles:
    - role: authorized_keys
      become: true
    - aws_cliv2
    - dotfiles
    - umask
    - role: docker
      become: true
      vars:
        docker_repo_url: https://download.docker.com/linux/ubuntu
    - role: node
      vars:
        node_nvm_nodejs_org_mirror: https://nodejs.org/dist
