---
- name: "Set user home directory fact"
  hosts: local
  connection: local
  gather_facts: false
  roles:
    - user_home

- name: "Configure Ubuntu 22.04"
  hosts: local
  connection: local
  roles:
    - role: authorized_keys
      become: true
#  tasks:
#    - name: "Get AuthorizedKeysFile Path"
#      ansible.builtin.shell: |
#        sshd -T | awk -v key=authorizedkeysfile -F' ' '$1==key{print $2}'
#      become: true
#      register: sshd
#    - name: "Parse AuthorizedKeysFile Path"
#      ansible.builtin.set_fact:
#        auth_keys_file: "{{ sshd.stdout | replace('%%', '**') | replace('%h', ansible_env.HOME) | replace('%u', ansible_env.USER) | replace('**', '%') }}"
#    - name: "Add public key to AuthorizedKeysFile"
#      ansible.posix.authorized_key:
#        key: "{{ lookup('ansible.builtin.file', 'id_ed25519_lde.pub') }}"
#        manage_dir: false
#        path: "{{ auth_keys_file }}"
#        state: present
#        user: "{{ ansible_env.USER }}"
#      become: true
#    - name: "Set 0600 $USER:root to AuthorizedKeysFile"
#      ansible.builtin.file:
#        path: "{{ auth_keys_file }}"
#        owner: "{{ ansible_env.USER }}"
#        group: root
#        mode: "0600"
#      become: true
#    - debug:
#        msg: "{{ lookup('ansible.builtin.file', 'id_ed25519_lde.pub', rstrip=false) }}"
#    - debug:
#        var: auth_keys_file
