---
- name: "Check if nvm is installed"
  ansible.builtin.stat:
    path: "{{ node_nvm_dir }}"
  register: nvm_dir

- name: "Install and configure nvm"
  when: not nvm_dir.stat.exists
  block:
    - name: "Install nvm"
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/{{ node_nvm_version }}/install.sh | bash
        creates: "{{ node_nvm_dir }}/nvm.sh"
        executable: "/bin/bash"

    - name: "Configure nvm"
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          export NVM_DIR="{{ node_nvm_dir }}"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

- name: "Install Node (LTS)"
  ansible.builtin.shell:
    cmd: |
      . {{ node_nvm_dir }}/nvm.sh
      nvm install --lts
    creates: "{{ node_nvm_dir }}/versions/node/*/bin/node"
    executable: "/bin/bash"
  environment:
    NVM_NODEJS_ORG_MIRROR: "{{ node_nvm_nodejs_org_mirror }}"
